apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://polycopy-prometheus:9090
    isDefault: true
    editable: false

  - name: Postgres
    uid: postgres
    type: postgres
    access: proxy
    url: polycopy-postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: false
